package us.lump.lib.util;

import java.util.EventObject;

/**
 * An event generated by BackgroundList.
 *
 * @author Troy Bowman
 * @version $Revision: 1.1 $
 */

public class BackgroundListEvent extends EventObject {
  public enum Type {
    added, deleted, changed, filled
  }

  public enum Effect {
    single, all
  }

  private Type type;
  private Effect effect;
  private int row;

  public Type getType() {
    return type;
  }

  public Effect getEffect() {
    return effect;
  }

  public int getRow() {
    return row;
  }

  public BackgroundListEvent(Object source,
                             Type type,
                             Effect effect,
                             int row) {
    super(source);
    this.type = type;
    this.effect = effect;
    this.row = row;
  }
}
