package us.lump.envelope.client.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;

/**
 * .
 *
 * @author troy
 * @version $Id: MainContent.java,v 1.3 2007/08/18 23:20:11 troy Exp $
 */
public class MainContent extends JPanel {
  private JPanel contentPanel;
  private JTree heirarchyTree;
  private JTable transactionTable;
  private JSplitPane splitPane;
  private JScrollPane treeScrollPane;
  private JScrollPane tableScrollPane;
  private JLabel status;
  private JPanel statusPanel;

  public MainContent() {
    add(contentPanel);
    transactionTable.addMouseWheelListener(new MouseWheelListener() {
      public void mouseWheelMoved(MouseWheelEvent e) {
        //To change body of implemented methods use File | Settings | File Templates.
      }
    });
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT
   * edit this method OR call it in your code!
   */
  private void $$$setupUI$$$() {
    contentPanel = new JPanel();
    contentPanel.setLayout(new GridLayoutManager(2,
                                                 1,
                                                 new Insets(0, 0, 0, 0),
                                                 -1,
                                                 -1));
    splitPane = new JSplitPane();
    contentPanel.add(splitPane,
                     new GridConstraints(0,
                                         0,
                                         1,
                                         1,
                                         GridConstraints.ANCHOR_CENTER,
                                         GridConstraints.FILL_BOTH,
                                         GridConstraints
                                             .SIZEPOLICY_CAN_SHRINK
                                         | GridConstraints
                                             .SIZEPOLICY_CAN_GROW,
                                         GridConstraints
                                             .SIZEPOLICY_CAN_SHRINK
                                         | GridConstraints
                                             .SIZEPOLICY_WANT_GROW,
                                         null,
                                         new Dimension(200, 200),
                                         null,
                                         0,
                                         false));
    treeScrollPane = new JScrollPane();
    splitPane.setLeftComponent(treeScrollPane);
    heirarchyTree = new JTree();
    treeScrollPane.setViewportView(heirarchyTree);
    tableScrollPane = new JScrollPane();
    splitPane.setRightComponent(tableScrollPane);
    transactionTable = new JTable();
    tableScrollPane.setViewportView(transactionTable);
    statusPanel = new JPanel();
    statusPanel.setLayout(new GridLayoutManager(1,
                                                1,
                                                new Insets(0, 0, 0, 0),
                                                -1,
                                                -1));
    contentPanel.add(statusPanel,
                     new GridConstraints(1,
                                         0,
                                         1,
                                         1,
                                         GridConstraints.ANCHOR_CENTER,
                                         GridConstraints.FILL_BOTH,
                                         GridConstraints
                                             .SIZEPOLICY_CAN_SHRINK
                                         | GridConstraints
                                             .SIZEPOLICY_CAN_GROW,
                                         GridConstraints
                                             .SIZEPOLICY_CAN_SHRINK
                                         | GridConstraints
                                             .SIZEPOLICY_CAN_GROW,
                                         null,
                                         null,
                                         null,
                                         0,
                                         false));
    status = new JLabel();
    status.setText("Label");
    statusPanel.add(status,
                    new GridConstraints(0,
                                        0,
                                        1,
                                        1,
                                        GridConstraints.ANCHOR_WEST,
                                        GridConstraints.FILL_NONE,
                                        GridConstraints.SIZEPOLICY_FIXED,
                                        GridConstraints.SIZEPOLICY_FIXED,
                                        null,
                                        null,
                                        null,
                                        0,
                                        false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() { return contentPanel; }
}
