package us.lump.envelope.client.ui;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * A Transaction Form.
 * @author Troy Bowman
 * @version $Id: TransactionForm.java,v 1.1 2008/07/16 05:40:00 troy Exp $
 */
public class TransactionForm {
  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT
   * edit this method OR call it in your code!
   */
  private void $$$setupUI$$$() {
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(1,
                                           1,
                                           new Insets(0, 0, 0, 0),
                                           -1,
                                           -1));
  }
}
